USE PRACTICE

SELECT C.COMPANY_ID,COMPANY_NAME,DD.DEPT_ID,DD.DEPT_NAME,ED.EMP_ID,EA.NAME,GENDER,PHONE,EMAIL,START,ADDRESS,CITY,STATE,ZIP_CODE,BASIC_PAY,NET_PAY FROM
COMPANIES C INNER JOIN EMPLOYEES_DETAILS ED ON C.COMPANY_ID = ED.COMPANY_ID INNER JOIN EMP_DEPARTMENT EMPD ON ED.EMP_ID = EMPD.EMP_ID INNER JOIN DEPARTMENT_DETAILS DD
ON DD.DEPT_ID = EMPD.DEPT_ID INNER JOIN EMP_ADDRESS EA ON EA.NAME = ED.NAME INNER JOIN EMP_SALARY ES ON ES.EMP_ID = ED.EMP_ID

SELECT DEPT_ID,DEPT_NAME,EMP_ID,NAME FROM DEPARTMENT_DETAILS DD LEFT OUTER JOIN EMPLOYEES_DETAILS ED ON DD.DEPT_ID = ED.EMP_ID
SELECT DEPT_ID,DEPT_NAME,EMP_ID,NAME FROM DEPARTMENT_DETAILS DD RIGHT OUTER JOIN EMPLOYEES_DETAILS ED ON DD.DEPT_ID = ED.EMP_ID
SELECT DEPT_ID,DEPT_NAME,EMP_ID,NAME FROM DEPARTMENT_DETAILS DD FULL OUTER JOIN EMPLOYEES_DETAILS ED ON DD.DEPT_ID = ED.EMP_ID
SELECT DEPT_ID,DEPT_NAME,EMP_ID,NAME FROM DEPARTMENT_DETAILS DD JOIN EMPLOYEES_DETAILS ED ON DD.DEPT_ID = ED.EMP_ID

SELECT DD.DEPT_ID,DD.DEPT_NAME,EED.EMP_ID,NAME FROM DEPARTMENT_DETAILS DD INNER JOIN EMP_DEPARTMENT ED ON DD.DEPT_ID = ED.DEPT_ID 
INNER JOIN EMPLOYEES_DETAILS EED ON EED.EMP_ID = ED.EMP_ID

GO
CREATE VIEW COMPLETE_EMPLOYEE_DETAILS
AS
SELECT C.COMPANY_ID,COMPANY_NAME,DD.DEPT_ID,DD.DEPT_NAME,ED.EMP_ID,EA.NAME,GENDER,PHONE,EMAIL,START_DATE,ADDRESS,CITY,STATE,ZIP_CODE,BASIC_PAY,NET_PAY FROM
COMPANIES C INNER JOIN EMPLOYEES_DETAILS ED ON C.COMPANY_ID = ED.COMPANY_ID INNER JOIN EMP_DEPARTMENT EMPD ON ED.EMP_ID = EMPD.EMP_ID INNER JOIN DEPARTMENT_DETAILS DD
ON DD.DEPT_ID = EMPD.DEPT_ID INNER JOIN EMP_ADDRESS EA ON EA.NAME = ED.NAME INNER JOIN EMP_SALARY ES ON ES.EMP_ID = ED.EMP_ID

SELECT * FROM COMPLETE_EMPLOYEE_DETAILS

CREATE INDEX NAME_INDEX ON EMP_DEPARTMENT(DEPT_ID,DEPT_NAME)

SELECT * FROM EMP_ADDRESS WHERE NAME = (SELECT NAME FROM EMPLOYEES_DETAILS WHERE EMP_ID =1)
SELECT * FROM EMP_ADDRESS WHERE NAME = (SELECT NAME FROM EMPLOYEES_DETAILS WHERE EMP_ID = (SELECT EMP_ID FROM EMP_DEPARTMENT WHERE EMP_ID = 4))

GO
CREATE TRIGGER CHECK_EMPLOYEE_DETAIL ON EMPLOYEES_DETAILS
AFTER INSERT, UPDATE, DELETE
AS 
BEGIN
SELECT COUNT(*) AS COUNT FROM EMPLOYEES_DETAILS
END

SELECT * FROM EMPLOYEES_DETAILS

SELECT LTRIM('  Harini  ')
SELECT RTRIM('  Harini  ')
SELECT LEN('  Harini  ')
SELECT LEFT('Harini', 3)
SELECT RIGHT('Harini', 5)


GO
CREATE OR ALTER PROCEDURE [dbo].[ExceptionHandling]
(@COMPANY_ID INT,
@COMPANY_NAME VARCHAR(25))
AS
BEGIN TRY
INSERT INTO COMPANIES VALUES(@COMPANY_ID,@COMPANY_NAME)
END TRY
BEGIN CATCH
PRINT'Error Encountered'
END CATCH

GO 
CREATE OR ALTER PROCEDURE [dbo].[ConditionStatements]
(@EMP_ID INT,
@BASIC_PAY FLOAT)
AS
BEGIN
DECLARE @COUNT INT = (SELECT MAX(EMP_ID) FROM EMP_SALARY)
IF @EMP_ID >= 1 AND @EMP_ID <= @COUNT
UPDATE EMP_SALARY SET BASIC_PAY = @BASIC_PAY WHERE EMP_ID = @EMP_ID
ELSE 
PRINT 'Data Not Found'
END

SELECT * FROM EMPLOYEES_DETAILS ED INNER JOIN EMP_SALARY ES ON ED.EMP_ID = ES.EMP_ID 
WHERE ED.NAME = (SELECT NAME FROM EMP_ADDRESS WHERE NAME = 'Harini')

SELECT * FROM EMPLOYEES_DETAILS
INSERT INTO EMPLOYEES_DETAILS VALUES('Harini','M',9765421300,'Harini@gmail.com','2022-06-23',101)
--INSERT INTO EMP_ADDRESS VALUES('Lekkala','F','18D','Lekkala','Tamil Nadu',654123)

CREATE INDEX NEW_INDEX ON EMP_ADDRESS(NAME,ADDRESS,CITY,STATE)
CREATE UNIQUE INDEX UNIQUE_INDEX ON EMPLOYEES_DETAILS(PHONE,EMAIL)

SELECT LOWER('Harini')
SELECT UPPER('Lekkala')
SELECT GETDATE()
SELECT DAY(GETDATE())
SELECT MONTH(GETDATE())
SELECT YEAR(GETDATE())
SELECT DATEADD(MONTH,5,'2022-01-01')
SELECT IIF(5<3,2,4)
SELECT CAST('2022' AS INT)
SELECT CONVERT(INT,34.56)
SELECT ISNUMERIC('N')
SELECT ISNULL(NULL,'Ela')
SELECT LEFT('Harini',4)
SELECT RIGHT('Harini',5)
SELECT FLOOR(25.45)
SELECT CEILING(45.21)
SELECT ROUND(25.5478,1)
SELECT SUBSTRING('How you Doing',1,7)

GO
CREATE OR ALTER PROCEDURE [dbo].[AddProcedureForEmpAddress]
(@NAME VARCHAR(50),
@ADDRESS VARCHAR(25),
@CITY VARCHAR(25),
@STATE VARCHAR(25),
@ZIP_CODE INT)
AS
BEGIN
BEGIN TRY
INSERT INTO EMP_ADDRESS VALUES(@NAME,@ADDRESS,@CITY,@STATE,@ZIP_CODE)
END TRY
BEGIN CATCH
PRINT ERROR_MESSAGE()
END CATCH
END


/*IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_NAME = 'InsertEmpDepartment' AND ROUTINE_TYPE = 'PROCEDURE')
BEGIN
PRINT 'Procedure already exists'
END
ELSE
CREATE PROCEDURE [dbo].[InsertEmpDepartment]
(@EMP_ID AS INT,
@EMP_NAME VARCHAR(25),
@DEPT_ID INT,
@DEPT_NAME VARCHAR(25))
AS
BEGIN
INSERT INTO EMP_DEPARTMENT VALUES(@EMP_ID,@EMP_NAME,@DEPT_ID,@DEPT_NAME)
END
END*/

SELECT * FROM EMPLOYEES_DETAILS

SELECT EA.NAME FROM EMP_ADDRESS EA INNER JOIN EMPLOYEES_DETAILS ED ON EA.NAME = ED.NAME INNER JOIN EMP_SALARY ES ON ES.EMP_ID = ED.EMP_ID

GO
CREATE OR ALTER PROCEDURE [dbo].[InsertToAllTables]
(@COMPANY_ID INT,
@COMPANY_NAME VARCHAR(25),
@DEPT_ID INT,
@DEPT_NAME VARCHAR(25),
@EMP_ID INT,
@NAME VARCHAR(50),
@GENDER VARCHAR(2),
@PHONE FLOAT,
@EMAIL VARCHAR(50),
@START_DATE DATE,
@ADDRESS VARCHAR(25),
@CITY VARCHAR(25),
@STATE VARCHAR(25),
@ZIP_CODE INT,
@BASIC_PAY FLOAT,
@DEDUCTIONS FLOAT,
@TAXABLE_PAY FLOAT,
@INCOME_TAX FLOAT,
@NET_PAY FLOAT)
AS
BEGIN TRY
IF NOT EXISTS (SELECT COMPANY_NAME FROM COMPANIES WHERE COMPANY_NAME = @COMPANY_NAME)
BEGIN
INSERT INTO COMPANIES VALUES(@COMPANY_ID,@COMPANY_NAME)
END
IF NOT EXISTS (SELECT DEPT_NAME FROM DEPARTMENT_DETAILS WHERE DEPT_NAME = @DEPT_NAME)
BEGIN
INSERT INTO DEPARTMENT_DETAILS VALUES (@DEPT_ID,@DEPT_NAME)
END
IF NOT EXISTS (SELECT NAME FROM EMP_ADDRESS WHERE NAME = @NAME)
BEGIN
INSERT INTO EMP_ADDRESS VALUES(@NAME,@ADDRESS,@CITY,@STATE,@ZIP_CODE)
END
IF NOT EXISTS (SELECT EMP_ID FROM EMPLOYEES_DETAILS WHERE EMP_ID = @EMP_ID)
BEGIN
INSERT INTO EMPLOYEES_DETAILS VALUES(@EMP_ID,@NAME,@GENDER,@PHONE,@EMAIL,@START_DATE,@COMPANY_ID)
END
IF NOT EXISTS (SELECT NAME FROM EMP_SALARY WHERE NAME = @NAME)
BEGIN
INSERT INTO EMP_SALARY VALUES(@EMP_ID,@NAME,@BASIC_PAY,@DEDUCTIONS,@TAXABLE_PAY,@INCOME_TAX,@NET_PAY)
END
IF NOT EXISTS (SELECT NAME,DEPT_NAME FROM EMP_DEPARTMENT WHERE NAME = @NAME AND DEPT_NAME = @DEPT_NAME)
BEGIN
INSERT INTO EMP_DEPARTMENT VALUES(@EMP_ID,@NAME,@DEPT_ID,@DEPT_NAME)
END
END TRY
BEGIN CATCH
PRINT ERROR_MESSAGE()
END CATCH

SELECT * FROM EMPLOYEES_DETAILS
SELECT * FROM COMPANIES
SELECT * FROM EMP_SALARY--
SELECT * FROM EMP_ADDRESS
SELECT * FROM DEPARTMENT_DETAILS
SELECT * FROM EMP_DEPARTMENT--

EXEC InsertToAllTables 101,'ABC',15,'IT_Support',7,'Thamarai','M',9087654321,'thamarai@gmail.com','2022-6-24','18C','Tirupur','Tamil Nadu',645231,20000,200,300,500,19000

ALTER TABLE EMP_DEPARTMENT ALTER COLUMN EMP_NAME VARCHAR(50)
DELETE FROM EMPLOYEES_DETAILS WHERE NAME ='Thamarai'
DELETE FROM EMP_ADDRESS WHERE NAME ='Thamarai'
DELETE FROM DEPARTMENT_DETAILS WHERE DEPT_NAME ='IT_Support'
DELETE FROM EMP_SALARY WHERE NAME ='Thamarai'

DROP TABLE EMPLOYEES_DETAILS
DROP TABLE COMPANIES
DROP TABLE EMP_SALARY--
DROP TABLE EMP_ADDRESS
DROP TABLE DEPARTMENT_DETAILS
DROP TABLE EMP_DEPARTMENT